/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./assets/**/*.{vue,js,css}",
		"./components/**/*.{vue,js}",
		"./layouts/**/*.vue",
		"./pages/**/*.vue",
		"./plugins/**/*.{js,ts}",
		"./nuxt.config.{js,ts}",
	],
	theme: {
		extend: {
			keyframes: {
				"fade-in": {
					"0%": { opacity: "0%" },
					"100%": { opacity: "100%" },
				},
			},
			animation: {
				"fade-in": "fade-in 0.5s ease-in-out",
			},
			colors: {
				colorPrimaryLight: "#376a1f",
				colorOnPrimaryLight: "#ffffff",
				colorPrimaryContainerLight: "#b7f397",
				colorOnPrimaryContainerLight: "#042100",
				colorSecondaryLight: "#386a1e",
				colorOnSecondaryLight: "#ffffff",
				colorSecondaryContainerLight: "#b8f296",
				colorOnSecondaryContainerLight: "#052100",
				colorTertiaryLight: "#00696c",
				colorOnTertiaryLight: "#ffffff",
				colorTertiaryContainerLight: "#6ff6f9",
				colorOnTertiaryContainerLight: "#002021",
				colorErrorLight: "#B3261E",
				colorOnErrorLight: "#FFFFFF",
				colorErrorContainerLight: "#F9DEDC",
				colorOnErrorContainerLight: "#410E0B",
				colorOutlineLight: "#79747E",
				colorBackgroundLight: "#fdfdf5",
				colorOnBackgroundLight: "#1a1c17",
				colorSurfaceLight: "#ffffff",
				colorOnSurfaceLight: "#111111",
				colorSurfaceVariantLight: "#E7E0EC",
				colorOnSurfaceVariantLight: "#49454F",
				colorInverSeSurfaceLight: "#2f312c",
				colorInverSeOnSurfaceLight: "#f1f1ea",
				//DarkTheme
				colorPrimaryDark: "#9cd67e",
				colorOnPrimaryDark: "#0c3900",
				colorPrimaryContainerDark: "#1f5107",
				colorOnPrimaryContainerDark: "#b7f397",
				colorSecondaryDark: "#9dd67d",
				colorOnSecondaryDark: "#0e3900",
				colorSecondaryContainerDark: "#215106",
				colorOnSecondaryContainerDark: "#b8f296",
				colorTertiaryDark: "#4ddadd",
				colorOnTertiaryDark: "#003739",
				colorTertiaryContainerDark: "#004f51",
				colorOnTertiaryContainerDark: "#6ff6f9",
				colorErrorDark: "#F2B8B5",
				colorOnErrorDark: "#601410",
				colorErrorContainerDark: "#8C1D18",
				colorOnErrorContainerDark: "#F9DEDC",
				colorOutlineDark: "#938F99",
				colorBackgroundDark: "#111111",
				colorOnBackgroundDark: "#e3e3dc",
				colorSurfaceDark: "#1a1c17",
				colorOnSurfaceDark: "#e3e3dc",
				colorSurfaceVariantDark: "#49454F",
				colorOnSurfaceVariantDark: "#CAC4D0",
				colorInverSeSurfaceDark: "#e3e3dc",
				colorInverSeOnSurfaceDark: "#1a1c17",
			},
		},
	},
};
